- name: Set authorized key taken from file
  copy:
     src: "{{keypath }}"
     dest: /home/adminuiuser/.ssh/authorized_keys
     mode: '0644'
  register: add_identity_key
  tags:
   - secure_servers

- name: Disable password login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^(#\s*)?PasswordAuthentication '
    line: 'PasswordAuthentication no'
  when: add_identity_key is succeeded and not add_identity_key is skipped
  notify: restart sshd
  tags:
   - secure_servers
