---
- hosts: ui_servers
  become: true

  roles:
    - dockerinstallation
    - downloadupdateapprepo
    - copy_conf.toml
    - builddockerimage
    - startcontainer
    - startuiapp
    - updatedb  
    - secure_servers
         
     
